### PR TITLE
add RSI2 strategy

### PR DESCRIPTION
**Pull request by fengkiej**

### CODE REVIEW

**Comment by saleh-old** [comment]
`prepare()` gets executed on every candle. in your case what you need is the `__init__()` method:
https://docs.jesse-ai.com/docs/strategies/entering-and-exiting.html#init

**Comment by fengkiej** [comment]
@saleh-mir it is updated, please check again

**Comment by saleh-old** [comment]
One more thing. Because of the negative balance exception, you now need to pass fee_rate in your position sizing. Read example #2:

https://forum.jesse-ai.com/d/102-v082-is-released-possible-breaking-change-is-included

**Comment by fengkiej** [comment]
added fee_rate params for SMACrossover too

**Comment by saleh-old** [comment]
Awesome job

**Pull request merged**
