### PR TITLE
add SMACrossover strategy

### PR DESCRIPTION
**Pull request by fengkiej**
This strategy can be considered as _Hello World_ in world of algorithmic trading, it may help new user to familiarize themselves to Jesse structure and syntax.

### CODE REVIEW

**Comment by saleh-old** [comment]
Hey. This strategy is good. I have a suggestion to make it more beginner friendly:

instead of:
```py
sma(self.candles, self.vars["slow_sma_period"], "close")
```

write it as:

```py
sma(self.candles, 200)
```

**Comment by saleh-old** [comment]
Also instead of `from jesse.indicators import sma`, write `import jesse.indicators as ta` and then use it as `ta.sma`. Of course you way is correct, but this way is the default import when generating strategy files, and I think beginners might get confused by it.

**Comment by fengkiej** [comment]
@saleh-mir thank you! I has been updated your suggestions

**Comment by saleh-old** [comment]
Thank you. One more thing, could you please not use `should_long /should_short` inside `update_position`? In this case It works just fine, but I want to keep `should_long /should_short` known as the entry method only. 

I've found it causing issues in certain strategies. 

Sorry I didn't see it before

**Comment by fengkiej** [comment]
@saleh-mir changes updated 👍

**Comment by saleh-old** [comment]
Thank you so much

**Pull request merged**
